Repository Oncognier/cogroom-fe, pull requests merged in 2025-05, with the labels that each got.

#2 [FEAT] 프로젝트 초기 세팅 #1
  .eslintrc.json
  .github/ISSUE_TEMPLATE/docs-issue-template.md
  .github/ISSUE_TEMPLATE/feat-issue-template.md
  .github/ISSUE_TEMPLATE/fix-issue-template.md
  .github/ISSUE_TEMPLATE/refactor-template.mdrefactor-issue-template.md
  .github/ISSUE_TEMPLATE/release-issue-template.md
  .github/pull_request_template.md
  .gitignore
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  README.md
  next.config.ts
  package-lock.json
  package.json
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/api/.gitkeep
  src/app/layout.tsx
  src/app/page.tsx
  src/components/atoms/Button.stories.tsx
  src/components/atoms/Button.styled.ts
  src/components/atoms/Button.tsx
  src/components/molcules/.gitkeep
  src/constants/.gitkeep
  src/features/.gitkeep
  src/hooks/.gitkeep
  src/store/.gitkeep
  src/styles/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
  tsconfig.json
  vitest.config.ts
Labels: ⚙️ 환경설정

#5 [FEAT] Emotion 설정: App Router + SSR 대응 #4
  .babelrc
  package-lock.json
  package.json
  src/app/EmotionRegistry.tsx
  src/app/layout.tsx
Labels: ⚙️ 환경설정

#10 [FIX] @emotion/babel-plugin 제거 #9
  .babelrc
  package-lock.json
  package.json
Labels: 🐞 버그

#7 [FEAT] axiosInstance 생성 & 요청 및 응답 interceptor #6
  src/api/.gitkeep
  src/api/axios/axiosInstance.ts
  src/api/axios/interceptors.ts
  src/api/index.d.ts
  src/constants/httpStatusCode/httpStatusCode.ts
  src/utils/errors/HTTPError.ts
Labels: ⚙️ 환경설정

#11 [FEAT] msw 설정 #8
  package.json
  public/mockServiceWorker.js
  src/app/MSWProvider.tsx
  src/app/layout.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/server.ts
Labels: ⚙️ 환경설정

#15 [FIX] MSW ESlint 오류 수정 #14
  src/app/MSWProvider.tsx
  src/app/layout.tsx
  src/mocks/browser.ts
  src/mocks/server.ts
Labels: 🐞 버그

#19 [FIX] axios 관련 eslint 오류 수정 #18
  src/api/axios/axiosInstance.ts
  src/api/axios/interceptors.ts
  src/api/axios/types.ts
Labels: 🐞 버그

#22 [FIX] Pretendard 폰트 적용 #21
  src/app/layout.tsx
  src/styles/font.ts
  src/styles/typography.ts
Labels: 🐞 버그

#24 [FEAT] 엔드포인트 상수 정의 #23
  src/constants/api/api.ts
Labels: 🔥 기능 추가

#35 [FEAT] Switch 컴포넌트 구현 #33
  src/components/atoms/Switch/Switch.stories.tsx
  src/components/atoms/Switch/Switch.styled.ts
  src/components/atoms/Switch/Switch.tsx
Labels: 🔥 기능 추가

#40 [FEAT] 디자인 팀 피드백 반영 #39
  src/components/atoms/IconButton/IconButton.stories.tsx
  src/components/atoms/IconButton/IconButton.styled.ts
  src/components/atoms/IconButton/IconButton.tsx
  src/components/atoms/Radio/Radio.stories.tsx
  src/components/atoms/Radio/Radio.styled.ts
  src/components/atoms/Radio/Radio.tsx
  src/components/atoms/Switch/Switch.stories.tsx
  src/components/atoms/Switch/Switch.styled.ts
  src/components/atoms/Switch/Switch.tsx
  src/components/atoms/TextButton/TextButton.stories.tsx
  src/components/atoms/TextButton/TextButton.styled.ts
  src/components/atoms/TextButton/TextButton.tsx
  src/styles/InteractionOverlay.styled.ts
Labels: 🔥 기능 추가, ♻️ 리팩토링

#41 [FEAT] AvatarPerson 컴포넌트 구현 #37
  src/components/atoms/AvatarPerson/AvatarPerson.stories.tsx
  src/components/atoms/AvatarPerson/AvatarPerson.styled.ts
  src/components/atoms/AvatarPerson/AvatarPerson.tsx
  src/constants/.gitkeep
  src/constants/image.ts
Labels: 🔥 기능 추가
