Repository Oncognier/cogroom-fe, pull requests merged in 2025-06, with the labels that each got.

#51 [FEAT] Input, Textarea 컴포넌트 구현 #48
  .storybook/globalStylesStorybook.tsx
  .storybook/preview-head.html
  src/components/atoms/FormStatusMessage/FormStatusMessage.stories.tsx
  src/components/atoms/FormStatusMessage/FormStatusMessage.styled.ts
  src/components/atoms/FormStatusMessage/FormStatusMessage.tsx
  src/components/atoms/InputLabel/InputLabel.stories.tsx
  src/components/atoms/InputLabel/InputLabel.styled.ts
  src/components/atoms/InputLabel/InputLabel.tsx
  src/components/molcules/.gitkeep
  src/components/molecules/Input/Input.stories.tsx
  src/components/molecules/Input/Input.styled.ts
  src/components/molecules/Input/Input.tsx
  src/components/molecules/Textarea/Textarea.stories.tsx
  src/components/molecules/Textarea/Textarea.styled.ts
  src/components/molecules/Textarea/Textarea.tsx
  src/styles/globalStyles.ts
Labels: 🔥 기능 추가

#55 [FEAT] 기본 Modal 및 상태 관리 로직 구현 #52
  src/app/layout.tsx
  src/components/molecules/Input/Input.tsx
  src/components/organisms/Modal/Base/Base.stories.tsx
  src/components/organisms/Modal/Base/Base.tsx
  src/components/organisms/Modal/Base/ModalInstance/ModalInstance.styled.ts
  src/components/organisms/Modal/Base/ModalInstance/ModalInstance.tsx
  src/components/organisms/Modal/Login/Login.tsx
  src/components/organisms/Modal/modalConfig.ts
  src/lib/query/QueryProvider.tsx
  src/store/.gitkeep
  src/stores/createModalStore.ts
  src/stores/useModalStore.ts
  src/types/.gitkeep
  src/types/modalTypes.ts
Labels: 🔥 기능 추가

#60 [FEAT] 프론트 이슈사항 해결 #59
  src/api/authApis.ts
  src/api/axios/interceptors.ts
  src/app/OAuth/callback/page.tsx
  src/app/layout.tsx
  src/components/atoms/OutlinedButton/OutlinedButton.tsx
  src/components/atoms/SolidButton/SolidButton.tsx
  src/components/organisms/Header/Header.styled.tsx
  src/components/organisms/Header/Header.tsx
  src/components/organisms/Header/NavItem/NavItem.stories.tsx
  src/components/organisms/Header/NavItem/NavItem.styled.tsx
  src/components/organisms/Header/NavItem/NavItem.tsx
  src/components/organisms/Header/NavList/NavList.stories.tsx
  src/components/organisms/Header/NavList/NavList.styled.tsx
  src/components/organisms/Header/NavList/NavList.tsx
  src/components/organisms/Modal/Login/Login.tsx
  src/hooks/api/auth/useLoginMutation.ts
  src/mocks/data/auth/postLoginMockResponse.ts
  src/mocks/handlers/auth.ts
  src/types/auth.ts
Labels: 🐞 버그, ♻️ 리팩토링

#67 [FEAT] cd 설정 - Vercel 배포 시 디스코드 알림 #66
  .github/workflows/discord.yml
Labels: 🔥 기능 추가, ⚙️ 환경설정

#65 [FEAT] daily 페이지 구현 #57
  package-lock.json
  package.json
  src/api/dailyApis.ts
  src/api/streakApis.ts
  src/app/daily/_components/Calendar/Calendar.styled.ts
  src/app/daily/_components/Calendar/Calendar.tsx
  src/app/daily/_components/Calendar/DateCell/DataCell.styled.ts
  src/app/daily/_components/Calendar/DateCell/DataCell.tsx
  src/app/daily/_components/Question/Question.styled.ts
  src/app/daily/_components/Question/Question.tsx
  src/app/daily/_components/Streak/Streak.styled.tsx
  src/app/daily/_components/Streak/Streak.tsx
  src/app/daily/layout.tsx
  src/app/daily/page.tsx
  src/app/daily/styled.tsx
  src/assets/icons/checkcircle-alt.svg
  src/assets/icons/checkcircle-fill.svg
  src/assets/icons/checkcircle.svg
  src/components/molecules/Breadcrumb/Breadcrumb.stories.tsx
  src/components/molecules/Breadcrumb/Breadcrumb.styled.ts
  src/components/molecules/Breadcrumb/Breadcrumb.tsx
  src/components/organisms/Modal/Daily/Edit/DailyAnswerEdit.styled.ts
  src/components/organisms/Modal/Daily/Edit/DailyAnswerEdit.tsx
  src/components/organisms/Modal/Daily/Post/DailyAnswerPost.styled.ts
  src/components/organisms/Modal/Daily/Post/DailyAnswerPost.tsx
  src/components/organisms/Modal/modalConfig.ts
  src/constants/api.ts
  src/constants/common.ts
  src/constants/image.ts
  src/constants/queryKeys.ts
  src/hooks/api/daily/useEditDailyAnswer.ts
  src/hooks/api/daily/useGetDaily.ts
  src/hooks/api/daily/useSubmitDailyAnswer.ts
  src/hooks/api/member/useEditUserInfo.ts
  src/hooks/api/member/useGetUserInfo.ts
  src/hooks/api/member/useGetUserSummary.ts
  src/hooks/api/streak/useGetStreakDays.ts
  src/lib/query/QueryProvider.tsx
  src/mocks/data/daily/editDailyAnswer.ts
  src/mocks/data/daily/getDailyData.ts
  src/mocks/data/daily/submitDailyAnswer.ts
  src/mocks/data/streak/getStreakDaysData.ts
  src/mocks/handlers/daily.ts
  src/mocks/handlers/handlers.ts
  src/mocks/handlers/streak.ts
  src/styles/globalStyles.ts
  src/types/daily.ts
  src/types/streak.ts
  src/utils/formatDay.ts
  src/utils/getCalendar.ts
Labels: 🔥 기능 추가

#71 [FIX] 디스코드 알림 워크플로우 버그 해결 #70
  .github/workflows/discord.yml
Labels: 🐞 버그

#79 [REFACTOR] delete enter handler #78
  src/app/daily/_components/Question/Question.tsx
  src/mocks/handlers/daily.ts
Labels: ♻️ 리팩토링

#88 [FEAT] TabBar 컴포넌트 구현 #87
  src/components/atoms/TabBar/TabBar.stories.tsx
  src/components/atoms/TabBar/TabBar.styled.ts
  src/components/atoms/TabBar/TabBar.tsx
Labels: 🔥 기능 추가

#90 [FEAT] 로그아웃 구현 #86
  src/api/authApis.ts
  src/app/mypage/_components/Sidebar/Sidebar.tsx
  src/components/atoms/OutlinedButton/OutlinedButton.styled.ts
  src/components/atoms/OutlinedButton/OutlinedButton.tsx
  src/components/organisms/Modal/Logout/Logout.styled.ts
  src/components/organisms/Modal/Logout/Logout.tsx
  src/components/organisms/Modal/Signup/Steps/CheckEmail/CheckEmail.tsx
  src/components/organisms/Modal/modalConfig.ts
  src/constants/queryKeys.ts
  src/hooks/api/auth/useLogout.ts
  src/mocks/data/auth/logoutData.ts
  src/mocks/handlers/auth.ts
Labels: 🔥 기능 추가

#89 [FEAT] 비회원이 마이페이지 직접 접근 시 접근 제한 추가 #85
  src/app/mypage/layout.tsx
  src/components/organisms/AuthGuard/AuthGuard.styled.ts
  src/components/organisms/AuthGuard/AuthGuard.tsx
Labels: 🔥 기능 추가

#94 [FEAT] EmptyState 컴포넌트 구현 #93
  src/assets/icons/message-circle-x.svg
  src/assets/icons/script-x.svg
  src/components/organisms/EmptyState/EmptyState.stories.tsx
  src/components/organisms/EmptyState/EmptyState.styled.ts
  src/components/organisms/EmptyState/EmptyState.tsx
Labels: 🔥 기능 추가

#95 [REFACTOR] 공통 레이아웃 분리를 위한 app 폴더 구조 리팩토링 #92
  src/app/(shared)/(anomaly)/(home)/page.tsx
  src/app/(shared)/(anomaly)/layout.styled.ts
  src/app/(shared)/(anomaly)/layout.tsx
  src/app/(shared)/(standard)/community/page.tsx
  src/app/(shared)/(standard)/content/page.tsx
  src/app/(shared)/(standard)/daily/_components/Calendar/Calendar.styled.ts
  src/app/(shared)/(standard)/daily/_components/Calendar/Calendar.tsx
  src/app/(shared)/(standard)/daily/_components/Calendar/DateCell/DataCell.styled.ts
  src/app/(shared)/(standard)/daily/_components/Calendar/DateCell/DataCell.tsx
  src/app/(shared)/(standard)/daily/_components/Question/Question.styled.ts
  src/app/(shared)/(standard)/daily/_components/Question/Question.tsx
  src/app/(shared)/(standard)/daily/_components/Streak/Streak.styled.tsx
  src/app/(shared)/(standard)/daily/_components/Streak/Streak.tsx
  src/app/(shared)/(standard)/daily/layout.styled.ts
  src/app/(shared)/(standard)/daily/layout.tsx
  src/app/(shared)/(standard)/daily/page.styled.ts
  src/app/(shared)/(standard)/daily/page.tsx
  src/app/(shared)/(standard)/layout.styled.ts
  src/app/(shared)/(standard)/layout.tsx
  src/app/(shared)/(standard)/mypage/_components/MyPageBreadcrumb/MyPageBreadcrumb.tsx
  src/app/(shared)/(standard)/mypage/_components/Sidebar/Sidebar.styled.ts
  src/app/(shared)/(standard)/mypage/_components/Sidebar/Sidebar.tsx
  src/app/(shared)/(standard)/mypage/_components/Sidebar/SidebarNavItem/SidebarNavItem.styled.ts
  src/app/(shared)/(standard)/mypage/_components/Sidebar/SidebarNavItem/SidebarNavItem.tsx
  src/app/(shared)/(standard)/mypage/community/page.tsx
  src/app/(shared)/(standard)/mypage/history/page.tsx
  src/app/(shared)/(standard)/mypage/layout.styled.ts
  src/app/(shared)/(standard)/mypage/layout.tsx
  src/app/(shared)/(standard)/mypage/notification/page.tsx
  src/app/(shared)/(standard)/mypage/page.tsx
  src/app/(shared)/(standard)/mypage/purchase/page.tsx
  src/app/(shared)/(standard)/mypage/setting/_components/EmailForm/EmailForm.styled.ts
  src/app/(shared)/(standard)/mypage/setting/_components/EmailForm/EmailForm.tsx
  src/app/(shared)/(standard)/mypage/setting/_components/SettingProfile/SettingProfile.styled.ts
  src/app/(shared)/(standard)/mypage/setting/_components/SettingProfile/SettingProfile.tsx
  src/app/(shared)/(standard)/mypage/setting/page.styled.ts
  src/app/(shared)/(standard)/mypage/setting/page.tsx
  src/app/(shared)/layout.tsx
  src/app/daily/layout.styled.ts
  src/app/daily/layout.tsx
  src/app/daily/page.styled.ts
  src/app/daily/page.tsx
  src/app/layout.tsx
  src/features/.gitkeep
Labels: ♻️ 리팩토링

#102 [FEAT] accessToken 저장 및 로그인/회원가입 후 라우팅 처리 개선 #101
  src/components/organisms/Header/Header.tsx
  src/components/organisms/Header/RightNav/RightNav.tsx
  src/hooks/api/auth/useLogin.ts
  src/hooks/api/auth/useSignup.ts
  src/utils/api/prefetchAuthAndUser.ts
Labels: 🔥 기능 추가, ♻️ 리팩토링

#104 [FEAT] daily streaks api enabled #99
  src/hooks/api/daily/useGetDaily.ts
  src/hooks/api/streak/useGetStreakDays.ts
Labels: 🔥 기능 추가, ♻️ 리팩토링

#100 [FEAT] 마이페이지 > 구매 기록 구현 #98
  src/app/(shared)/(standard)/mypage/purchase/layout.styled.ts
  src/app/(shared)/(standard)/mypage/purchase/layout.tsx
  src/app/(shared)/(standard)/mypage/purchase/page.tsx
Labels: 🔥 기능 추가

#108 [FEAT] 마이페이지 > 커뮤니티 활동 구현 #96
  src/app/(shared)/(standard)/mypage/community/comments/page.tsx
  src/app/(shared)/(standard)/mypage/community/layout.styled.ts
  src/app/(shared)/(standard)/mypage/community/layout.tsx
  src/app/(shared)/(standard)/mypage/community/likes/page.tsx
  src/app/(shared)/(standard)/mypage/community/page.tsx
  src/app/(shared)/(standard)/mypage/community/posts/page.tsx
  src/components/molecules/TabBarList/TabBarList.styled.ts
  src/components/molecules/TabBarList/TabBarList.tsx
Labels: 🔥 기능 추가

#115 [FIX] 토큰 재발급 api 엔드포인트 변경 #114
  src/constants/api.ts
Labels: 🐞 버그

#117 [FIX] 토큰 재발급 버그 해결 #116
  src/api/authApis.ts
  src/api/axios/interceptors.ts
  src/utils/api/prefetchAuthAndUser.ts
Labels: 🐞 버그

#112 [FEAT] 마이페이지 > 푸시 및 카톡 알림 구현 #97
  src/app/(shared)/(standard)/mypage/notification/_components/SettingGroup/SettingGroup.styled.ts
  src/app/(shared)/(standard)/mypage/notification/_components/SettingGroup/SettingGroup.tsx
  src/app/(shared)/(standard)/mypage/notification/_components/SettingGroup/SettingItem/SettingItem.styled.ts
  src/app/(shared)/(standard)/mypage/notification/_components/SettingGroup/SettingItem/SettingItem.tsx
  src/app/(shared)/(standard)/mypage/notification/layout.styled.ts
  src/app/(shared)/(standard)/mypage/notification/layout.tsx
  src/app/(shared)/(standard)/mypage/notification/page.styled.ts
  src/app/(shared)/(standard)/mypage/notification/page.tsx
Labels: 🔥 기능 추가

#127 [FIX] 로그아웃 후 헤더 상태 미갱신 이슈 #126
  src/api/axios/interceptors.ts
  src/components/organisms/Header/RightNav/RightNav.tsx
  src/constants/api.ts
  src/hooks/api/auth/useLogout.ts
  src/utils/api/prefetchAuthAndUser.ts
Labels: 🐞 버그

#132 [REFACTOR] axios 인터셉터 리팩토링 #130
  src/api/authApis.ts
  src/api/axios/axiosInstance.ts
  src/api/axios/requestInterceptors.ts
  src/api/axios/responseInterceptors.ts
  src/api/axios/types.ts
  src/constants/api.ts
  src/lib/query/QueryProvider.tsx
  src/utils/api/prefetchAuthAndUser.ts
Labels: ♻️ 리팩토링

#135 [REFACTOR] 모킹 리팩토링 #134
  src/mocks/data/auth/checkEmailVerifiedData.ts
  src/mocks/data/auth/loginData.ts
  src/mocks/data/auth/reissueTokenData.ts
  src/mocks/data/auth/sendEmailData.ts
  src/mocks/data/auth/signupData.ts
  src/mocks/data/daily/editDailyAnswer.ts
  src/mocks/data/daily/getDailyData.ts
  src/mocks/data/daily/submitDailyAnswer.ts
  src/mocks/data/file/getPresignedUrlData.ts
  src/mocks/data/member/editUserInfoData.ts
  src/mocks/data/member/getUserDashboardData.ts
  src/mocks/data/member/getUserInfoData.ts
  src/mocks/data/member/getUserSummaryData.ts
  src/mocks/data/streak/getStreakDaysData.ts
  src/mocks/handlers/daily.ts
  src/mocks/handlers/streak.ts
Labels: ♻️ 리팩토링

#137 [FEAT] 이미지 업로드 API 수정 #80
  src/api/fileApis.ts
  src/app/(shared)/(standard)/mypage/setting/_components/SettingProfile/SettingProfile.tsx
  src/app/(shared)/(standard)/mypage/setting/page.tsx
  src/components/atoms/IconButton/IconButton.tsx
  src/constants/api.ts
  src/hooks/api/file/useUploadFileToS3.ts
  src/mocks/data/file/getPresignedUrlData.ts
  src/mocks/handlers/file.ts
  src/types/file.ts
Labels: 🔥 기능 추가

#139 [FEAT] 어드민 페이지 라우팅 구조 구현 #138
  src/app/(shared)/(standard)/admin/contents/page.tsx
  src/app/(shared)/(standard)/admin/layout.styled.ts
  src/app/(shared)/(standard)/admin/layout.tsx
  src/app/(shared)/(standard)/admin/notices/page.tsx
  src/app/(shared)/(standard)/admin/page.tsx
  src/app/(shared)/(standard)/admin/payments/page.tsx
  src/app/(shared)/(standard)/admin/users/page.tsx
Labels: 🔥 기능 추가

#136 [FEAT] 폼 유효성 검사 추가 #103
  src/api/authApis.ts
  src/app/(shared)/(standard)/mypage/setting/_components/EmailForm/EmailForm.styled.ts
  src/app/(shared)/(standard)/mypage/setting/_components/EmailForm/EmailForm.tsx
  src/app/(shared)/(standard)/mypage/setting/page.tsx
  src/components/atoms/FormStatusMessage/FormStatusMessage.stories.tsx
  src/components/atoms/FormStatusMessage/FormStatusMessage.styled.ts
  src/components/atoms/FormStatusMessage/FormStatusMessage.tsx
  src/components/molecules/Input/Input.tsx
  src/components/molecules/Textarea/Textarea.tsx
  src/components/organisms/Modal/Signup/Signup.tsx
  src/components/organisms/Modal/Signup/Steps/InputEmail/InputEmail.tsx
  src/components/organisms/Modal/Signup/Steps/VerifyEmail/VerifyEmail.tsx
  src/constants/validationMessages.ts
  src/hooks/api/auth/useCheckEmailVerified.ts
  src/hooks/api/auth/useSendEmail.ts
  src/hooks/api/member/useEditUserInfo.ts
  src/mocks/data/auth/checkEmailVerifiedData.ts
  src/types/auth.ts
  src/types/form.ts
  src/utils/formatAutoComplete.ts
  src/utils/validators/emailValidators.ts
  src/utils/validators/setValidationError.ts
  src/utils/validators/userValidators.ts
Labels: 🔥 기능 추가

#148 [FEAT] NumberPagination 컴포넌트 구현 #147
  src/components/molecules/NumberPagination/NumberPagination.stories.tsx
  src/components/molecules/NumberPagination/NumberPagination.styled.ts
  src/components/molecules/NumberPagination/NumberPagination.tsx
  src/constants/common.ts
  src/utils/pagination.ts
Labels: 🔥 기능 추가

#154 [REFACTOR] Check 컴포넌트명 수정 #153
  src/components/atoms/Check/Check.stories.tsx
  src/components/atoms/Check/Check.styled.ts
  src/components/atoms/Check/Check.tsx
  src/components/atoms/Checkbox/Checkbox.stories.tsx
  src/components/atoms/Checkbox/Checkbox.styled.ts
  src/components/atoms/Checkbox/Checkbox.tsx
Labels: ♻️ 리팩토링

#155 [FEAT] Select 컴포넌트 구현 #150
  src/components/atoms/Checkbox/Checkbox.tsx
  src/components/atoms/DropdownItem/DropdownItem.styled.ts
  src/components/atoms/DropdownItem/DropdownItem.tsx
  src/components/atoms/Radio/Radio.tsx
  src/components/molecules/DropdownList/DropdownList.styled.ts
  src/components/molecules/DropdownList/DropdownList.tsx
  src/components/molecules/Select/Select.stories.tsx
  src/components/molecules/Select/Select.styled.ts
  src/components/molecules/Select/Select.tsx
  src/components/molecules/Select/SelectTagList/SelectTag/SelectTag.styled.ts
  src/components/molecules/Select/SelectTagList/SelectTag/SelectTag.tsx
  src/components/molecules/Select/SelectTagList/SelectTagList.styled.ts
  src/components/molecules/Select/SelectTagList/SelectTagList.tsx
  src/hooks/useDropdown.ts
  src/styles/foundation.ts
  src/styles/types.ts
  src/types/common.ts
Labels: 🔥 기능 추가

#163 [FEAT] DailyListRow 컴포넌트 구현 #162
  src/app/(shared)/(standard)/admin/_components/DailyListRow/DailyListRow.styled.ts
  src/app/(shared)/(standard)/admin/_components/DailyListRow/DailyListRow.tsx
  src/constants/common.ts
  src/types/daily.ts
Labels: 🔥 기능 추가

#165 [FEAT] 어드민 > 회원관리 > 데일리콘텐츠 구현 #164
  src/api/adminApi.ts
  src/app/(shared)/(standard)/admin/_components/DailyListRow/DailyListRow.tsx
  src/app/(shared)/(standard)/admin/users/[memberId]/daily/_components/DailyTableHeader/DailyTableHeader.styled.ts
  src/app/(shared)/(standard)/admin/users/[memberId]/daily/_components/DailyTableHeader/DailyTableHeader.tsx
  src/app/(shared)/(standard)/admin/users/[memberId]/daily/page.styled.ts
  src/app/(shared)/(standard)/admin/users/[memberId]/daily/page.tsx
  src/constants/common.ts
  src/constants/queryKeys.ts
  src/hooks/api/admin/useGetMemberDailyQuestions.ts
  src/mocks/data/admin/getMemberDailyQuestionsData.ts
  src/mocks/handlers/admin.ts
  src/types/admin.ts
  src/types/form.ts
Labels: 🔥 기능 추가

#169 [FEAT] 어드민 > 콘텐츠관리 > 데일리 콘텐츠 #166
  package-lock.json
  package.json
  src/api/adminApi.ts
  src/api/axios/axiosInstance.ts
  src/app/(shared)/(standard)/admin/contents/_components/ContentsDailyTableHeader/ContentsDailyTableHeader.styled.ts
  src/app/(shared)/(standard)/admin/contents/_components/ContentsDailyTableHeader/ContentsDailyTableHeader.tsx
  src/app/(shared)/(standard)/admin/contents/page.styled.ts
  src/app/(shared)/(standard)/admin/contents/page.tsx
  src/app/(shared)/(standard)/admin/users/[memberId]/daily/page.tsx
  src/app/(shared)/(standard)/admin/users/page.tsx
  src/constants/common.ts
  src/hooks/api/admin/useGetDailyQuestions.ts
  src/hooks/api/admin/useGetMemberDailyQuestions.ts
  src/mocks/data/admin/getDailyQuestionsData.ts
  src/mocks/handlers/admin.ts
  src/types/admin.ts
Labels: 🔥 기능 추가

#183 [FEAT] 데일리 공유하기 기능 구현 #125
  global.d.ts
  src/app/(shared)/(standard)/daily/layout.tsx
  src/app/(shared)/(standard)/daily/page.styled.ts
  src/app/(shared)/(standard)/daily/page.tsx
  src/app/(shared)/(standard)/mypage/_components/StreakSummaryCard/StreakSummaryCard.tsx
  src/app/(shared)/(standard)/mypage/page.tsx
  src/app/KakaoInitializer.tsx
  src/app/ModalProvider.tsx
  src/app/layout.tsx
  src/assets/icons/upload.svg
  src/components/organisms/Modal/Alert/Alert.styled.ts
  src/components/organisms/Modal/Alert/Alert.tsx
  src/components/organisms/Modal/Daily/DailyShare/DailyShare.styled.ts
  src/components/organisms/Modal/Daily/DailyShare/DailyShare.tsx
  src/components/organisms/Modal/modalConfig.ts
  src/constants/common.ts
  src/constants/image.ts
  src/utils/api/kakaoShare.ts
Labels: 🔥 기능 추가
