Repository Oncognier/cogroom-fe, pull requests merged in 2025-09, with the labels that each got.

#476 [FEAT] 커뮤니티 > 글 수정페이지 추가 #446
  src/api/postApis.ts
  src/app/(shared)/(standard)/community/post/[id]/_components/PostAuthor/PostAuthor.tsx
  src/app/(shared)/(standard)/community/write/_components/CategorySelector/CategorySelector.styled.ts
  src/app/(shared)/(standard)/community/write/_components/CategorySelector/CategorySelector.tsx
  src/app/(shared)/(standard)/community/write/_components/DailyQuestionCard/DailyQuestionCard.tsx
  src/app/(shared)/(standard)/community/write/_components/PostEditor/PostEditor.styled.ts
  src/app/(shared)/(standard)/community/write/_components/PostEditor/PostEditor.tsx
  src/app/(shared)/(standard)/community/write/_components/TitleInput/TitleInput.tsx
  src/app/(shared)/(standard)/community/write/page.tsx
  src/components/organisms/Editor/CustomImage.tsx
  src/components/organisms/Editor/Editor.tsx
  src/constants/api.ts
  src/hooks/api/post/useGetPost.ts
  src/hooks/api/post/useUpdatePost.ts
  src/hooks/useCommunityWriteLogic.ts
  src/types/communityWrite.ts
  src/types/post.ts
  src/utils/postUtils.ts
Labels: 🔥 기능 추가

#481 [FEAT] 커뮤니티 > 게시글 조회 페이지 내 수정/삭제 기능 추가 #477
  src/app/(shared)/(standard)/community/post/[id]/_components/PostAuthor/PostAuthor.styled.ts
  src/app/(shared)/(standard)/community/post/[id]/_components/PostAuthor/PostAuthor.tsx
  src/components/organisms/Modal/CommunityDelete/CommunityDelete.tsx
  src/hooks/api/post/useDeletePost.ts
Labels: 🔥 기능 추가

#484 [FEAT] 에디터 > 새 창으로 열기 기능 추가 및 기타 수정 #464
  package-lock.json
  src/components/organisms/Editor/CustomToolbar/Popup/ColorPopup.tsx
  src/components/organisms/Editor/Editor.tsx
Labels: 🔥 기능 추가

#489 [FEAT] daily answer character limit #487
  src/app/(shared)/(standard)/daily/_components/Question/Question.tsx
  src/app/(shared)/(standard)/daily/_components/Question/_components/InputCount.styled.ts
  src/app/(shared)/(standard)/daily/_components/Question/_components/InputCount.tsx
  src/constants/common.ts
  src/hooks/useTextLimiter.ts
Labels: 🔥 기능 추가, ♻️ 리팩토링

#486 [FEAT] 커뮤니티 > 게시글 조회 페이지 > 게시글 댓글 영역 추가 #463
  src/api/commentApis.ts
  src/app/(shared)/(standard)/community/post/[id]/_components/PostComments/PostComments.styled.ts
  src/app/(shared)/(standard)/community/post/[id]/_components/PostComments/PostComments.tsx
  src/app/(shared)/(standard)/community/post/[id]/_components/PostLikesSaved/PostLikesSaved.styled.ts
  src/app/(shared)/(standard)/community/post/[id]/page.tsx
  src/components/molecules/CommentField/CommentField.styled.ts
  src/components/molecules/CommentField/CommentField.tsx
  src/components/molecules/CommentItem/CommentItem.styled.ts
  src/components/molecules/CommentItem/CommentItem.tsx
  src/components/molecules/CommentList/CommentList.styled.ts
  src/components/molecules/CommentList/CommentList.tsx
  src/components/organisms/Modal/CommunityDelete/CommunityDelete.tsx
  src/constants/api.ts
  src/hooks/api/comment/useCreateComment.ts
  src/hooks/api/comment/useDeleteComment.ts
  src/hooks/api/comment/useDeleteCommentLike.ts
  src/hooks/api/comment/useGetComments.ts
  src/hooks/api/comment/useToggleCommentLike.ts
  src/hooks/api/comment/useUpdateComment.ts
  src/hooks/api/post/useCreatePost.ts
  src/types/comment.ts
Labels: 🔥 기능 추가

#499 [FEAT] 커뮤니티 관련 자잘한 이슈 수정 #498
  src/app/(shared)/(standard)/daily/_components/Question/Question.styled.ts
  src/app/(shared)/(standard)/daily/_components/Question/Question.tsx
  src/app/(shared)/(standard)/mypage/community/comments/page.tsx
  src/app/(shared)/(standard)/mypage/community/layout.tsx
  src/app/(shared)/(standard)/mypage/community/posts/page.styled.ts
  src/app/(shared)/(standard)/mypage/community/posts/page.tsx
  src/app/(shared)/(standard)/mypage/community/saves/page.tsx
Labels: 🔥 기능 추가

#502 [FEAT] 에디터 > 링크 새창으로 열기 기능추가 #495
  src/app/(shared)/(standard)/community/post/[id]/_components/PostContent/PostContent.styled.ts
  src/app/(shared)/(standard)/community/post/[id]/_components/PostContent/PostContent.tsx
  src/components/organisms/Editor/CustomLink.ts
  src/components/organisms/Editor/CustomToolbar/Popup/LinkPopup.tsx
  src/components/organisms/Editor/CustomToolbar/Sections/CustomToolbarPalette.tsx
  src/components/organisms/Editor/Editor.tsx
Labels: 🔥 기능 추가

#508 [FEAT] 에디터 > 이미지 정렬 기능 #505
  package-lock.json
  package.json
  src/components/organisms/Editor/CustomImage.tsx
  src/components/organisms/Editor/CustomToolbar/Sections/CustomToolbarParagraph.tsx
Labels: 🔥 기능 추가

#514 [FEAT] CommentListRow 탭, 모바일 반응형 구현 #504
  src/app/(shared)/(standard)/mypage/_components/CommentListRow/CommentListRow.styled.ts
Labels: 🔥 기능 추가

#518 [FEAT] 커뮤니티 반응형 추가 #517
  src/app/(shared)/(standard)/community/_components/PostList/PostList.styled.ts
Labels: 🔥 기능 추가

#524 [FIX] searchfilter date params #513
  src/app/(shared)/(standard)/mypage/community/comments/page.tsx
  src/app/(shared)/(standard)/mypage/community/likes/comments/page.tsx
  src/app/(shared)/(standard)/mypage/community/likes/posts/page.tsx
  src/app/(shared)/(standard)/mypage/community/posts/page.tsx
  src/app/(shared)/(standard)/mypage/community/saves/page.tsx
  src/hooks/useUrlSearchParams.ts
Labels: 🐞 버그

#535 [FEAT] 커뮤니티 > 글작성 페이지 반응형 작업 #523
  src/app/(shared)/(standard)/community/post/[id]/_components/PostContent/PostContent.styled.ts
  src/app/(shared)/(standard)/community/write/_components/DailyQuestionCard/DailyQuestionCard.tsx
  src/app/(shared)/(standard)/community/write/_components/DailyQuestionCard/DailyQuestionCardMobile.tsx
  src/app/(shared)/(standard)/community/write/_components/PostEditor/PostEditor.tsx
  src/app/(shared)/(standard)/community/write/_components/TitleInput/TitleInput.tsx
  src/app/(shared)/(standard)/community/write/page.styled.ts
  src/app/(shared)/(standard)/community/write/page.tsx
  src/components/organisms/Editor/CustomImage.tsx
  src/components/organisms/Editor/CustomToolbar/CustomToolbar.styled.ts
  src/components/organisms/Editor/CustomToolbar/CustomToolbar.tsx
  src/components/organisms/Editor/CustomToolbar/Popup/ColorPopup.tsx
  src/components/organisms/Editor/CustomToolbar/Popup/LinkPopup.tsx
  src/components/organisms/Editor/CustomToolbar/Popup/PopupStyles.styled.ts
  src/components/organisms/Editor/CustomToolbar/Popup/PopupWrapper.tsx
  src/components/organisms/Editor/CustomToolbar/Sections/CustomToolbarAlignment.tsx
  src/components/organisms/Editor/CustomToolbar/Sections/CustomToolbarList.tsx
  src/components/organisms/Editor/CustomToolbar/Sections/CustomToolbarPalette.tsx
  src/components/organisms/Editor/CustomToolbar/Sections/CustomToolbarUtilities.tsx
  src/components/organisms/Editor/Editor.styled.ts
  src/components/organisms/Editor/Editor.tsx
  src/hooks/api/file/useUploadFileToS3.ts
  src/hooks/api/post/useUpdatePost.ts
  src/utils/postUtils.ts
Labels: 🔥 기능 추가

#539 [FEAT] SearchFilter 반응형 추가 #538
  src/app/(shared)/(standard)/mypage/_components/MyPageScrollXWrapper/MyPageScrollXWrapper.styled.ts
  src/app/(shared)/(standard)/mypage/_components/MyPageScrollXWrapper/MyPageScrollXWrapper.tsx
  src/app/(shared)/(standard)/mypage/community/comments/page.tsx
  src/app/(shared)/(standard)/mypage/community/likes/comments/page.tsx
  src/app/(shared)/(standard)/mypage/community/likes/posts/page.tsx
  src/app/(shared)/(standard)/mypage/community/posts/page.tsx
  src/app/(shared)/(standard)/mypage/community/saves/page.tsx
  src/assets/icons/filter.svg
  src/components/atoms/SolidButton/SolidButton.styled.ts
  src/components/atoms/SolidButton/SolidButton.tsx
  src/components/molecules/SearchFilter/SearchFilter.styled.ts
  src/components/molecules/SearchFilter/SearchFilter.tsx
Labels: 🔥 기능 추가

#548 [FIX] PostCard 회원/비회원 처리 수정 #547
  src/components/organisms/PostCard/PostCardDesktop/PostCardDesktop.tsx
Labels: 🐞 버그
